version: "3.7"

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql_docker
    ports:
      - '3307:3306'
    environment: 
      MYSQL_SERVER: db
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    volumes:
      - app-db:/var/lib/mysql

volumes: 
  app-db: